name: Build and Deploy

# Only build and deploy after new tag.
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node with yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build Astro
        run: yarn build

      - name: Deploy website to host
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/
          port: 21

      - name: Output Deploy
        run: |
          echo "Website Deployed"
