name: Build

# Only build after new tag.
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node with yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build Astro
        run: yarn build

      - name: Enter dist folder
        run: cd dist/

      - name: Push to release branch
        run: |
          mkdir release
          git init --initial-branch=release
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "build: Add new release files"
          git push --force
