name: Build

# Only build after new tag.
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node with yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build Astro
        run: yarn build

      - name: Enter dist folder
        run: cd dist/

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'feat: Add new build'
          branch: release
          disable_globbing: true
          skip_dirty_check: true
